name: Go

on: [push, pull_request]

permissions:
  contents: read

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ^1.23
      id: go
    
    - name: Install libzmq
      run: sudo apt-get install libzmq3-dev

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -v .

    - name: Make data directories
      run: mkdir stores/data

    - name: Test
      run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

    - uses: codecov/codecov-action@v1
      with:
        file: ./coverage.txt
