name: Go

on: [push, pull_request]

permissions:
  contents: read

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ^1.24
      id: go
    
    - name: Install libzmq
      run: sudo apt-get install libzmq3-dev

    - name: Get dependencies
      run: |
        go get -v -t ./...

    - name: Build
      run: go build -v .

    - name: Make data directories
      run: mkdir stores/data

    - name: Test
      run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

    - uses: codecov/codecov-action@v5
      with:
        files: ./coverage.txt
        token: ${{ secrets.CODECOV_TOKEN }}
